#!/usr/bin/env python

import xmlrpclib

server="localhost"
user="lliurex"
password="lliurex"

c=xmlrpclib.ServerProxy("https://"+server+":9779")
user_info=(user,password)

print(c.load_exports(user_info,"ProxyManager"))
