#!/usr/bin/env python

import xmlrpclib

server="localhost"
user="lliurex"
password="lliurex"

c=xmlrpclib.ServerProxy("https://"+server+":9779")
user=(user,password)
#print c.get_methods('N4dProxy')
#se necesitan las siguientes variables del n4d-proxy
#INTERNAL_NETWORK
#INTERNAL_MASK
#SRV_IP

#se necesitan las siguientes variables del n4d-dnsmasq
#INTERNAL_DOMAIN

print c.load_exports(user,"N4dProxy")
